memory_limit=64M
max_execution_time=3
display_errors=1
log_errors=0
allow_url_fopen=0
allow_url_include=0
disable_functions=exec,shell_exec,system,passthru,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source
open_basedir=/workspace:/tmp:/sandbox

